//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greengrocery.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        public int order_id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> supplier_id { get; set; }
        public Nullable<int> customer_id { get; set; }
    
        public virtual customersGrocery customersGrocery { get; set; }
        public virtual employeesGrocery employeesGrocery { get; set; }
        public virtual productsGrocery productsGrocery { get; set; }
        public virtual suppliersGrocery suppliersGrocery { get; set; }
    }
}
